"""Minimal `whisper` shim for CosyVoice.

CosyVoice's frontend only calls ``whisper.log_mel_spectrogram(speech, n_mels=128)``.
The upstream ``openai-whisper`` sdist (20231117) fails to build on this image and
pulls heavy CUDA deps, so we provide a faithful, dependency-light reimplementation
that matches whisper's mel computation exactly (n_fft=400, hop=160, slaney-norm mel
filters generated by librosa — identical to the bundled assets/mel_filters.npz).
"""
from functools import lru_cache

import numpy as np
import torch
import torch.nn.functional as F

N_FFT = 400
HOP_LENGTH = 160
SAMPLE_RATE = 16000


@lru_cache(maxsize=None)
def _mel_filters(device, n_mels: int):
    import librosa

    filters = librosa.filters.mel(sr=SAMPLE_RATE, n_fft=N_FFT, n_mels=n_mels)
    return torch.from_numpy(filters).to(device)


def log_mel_spectrogram(audio, n_mels: int = 80, padding: int = 0, device=None):
    if not torch.is_tensor(audio):
        audio = torch.from_numpy(np.asarray(audio))
    audio = audio.float()
    if device is not None:
        audio = audio.to(device)
    if padding > 0:
        audio = F.pad(audio, (0, padding))
    window = torch.hann_window(N_FFT).to(audio.device)
    stft = torch.stft(
        audio, N_FFT, HOP_LENGTH, window=window, return_complex=True
    )
    magnitudes = stft[..., :-1].abs() ** 2

    filters = _mel_filters(audio.device, n_mels)
    mel_spec = filters @ magnitudes

    log_spec = torch.clamp(mel_spec, min=1e-10).log10()
    log_spec = torch.maximum(log_spec, log_spec.max() - 8.0)
    log_spec = (log_spec + 4.0) / 4.0
    return log_spec
